### PR TITLE
First complete implementation of all the methods

### PR DESCRIPTION
**Pull request by kelibst**
this branch contains the enumerable methods:
This project contains
-my_each my_each_with_index my_select my_all? my_any?
-my_none? my_count my_map my_inject

Also contains:

-multiply_els method to test my_inject_method
You can find the test case file that was used to check all the methods in sample_test_case.rb

Run ruby sample_text_case.rb if you have ruby installed to see the result.

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Very nice project!

It looks great and is coming into place, but we need to double-check some cases before continuing:

#### `my_each`

- [ ] returns an Enumerator if no block is given

```ruby
>> [1].each
=> #<Enumerator: [1]:each>
>> [1].my_each # LocalJumpError (no block given (yield))
```

#### `my_each_with_index`

- [ ] returns an enumerator if no block is given

```ruby
>> [1].each_with_index
=> #<Enumerator: [1]:each_with_index>
>> [1].my_each_with_index # LocalJumpError (no block given (yield))
```

#### `my_select`

- [ ] returns an enumerator if no block is given

```ruby
>> [1].select
=> #<Enumerator: [1]:select>
>> [1].my_select # LocalJumpError (no block given (yield))
```

#### `my_all?`

- [ ] when no block or argument is given returns true when none of the collection members are false or nil

```ruby
>> [1].all?
=> true
>> [1].my_all? # LocalJumpError (no block given (yield))
```

- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class

```ruby
>> [1].all?(Integer)
=> true
>> [1].my_all?(Integer)
=> false
```

- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

```ruby
>> [1].all?(1)
=> true
>> [1].my_all?(1)
=> false
```

#### `my_any?`

- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil

```ruby
>> [1].any?
=> true
>> [1].my_any? # LocalJumpError (no block given (yield))
```

- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class

```ruby
>> [1].any?(Integer)
=> true
>> [1].my_any?(Integer)
=> false
```

- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

```ruby
>> [1].any?(1)
=> true
>> [1].my_any?(1)
=> false
```

#### `my_none?`

- [ ] when no block or argument is given returns true only if none of the collection members is true

```ruby
>> [false].none?
=> true
>> [false].my_none? # LocalJumpError (no block given (yield))
```

- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class

```ruby
>> [1].none?(Integer)
=> false
>> [1].my_none?(Integer)
=> true
```

- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

```ruby
>> [1].none?(1)
=> false
>> [1].my_none?(1)
=> true
```

#### `my_map`

- [ ] returns an Enumerator if no block is given

```ruby
>> [1].map
=> #<Enumerator: [1]:map>
>> [1].my_map # LocalJumpError (no block given (yield))
```

#### `my_inject`

- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

```ruby
>> [1, 1].inject(:+)
=> 2
>> [1, 1].my_inject(:+) # LocalJumpError (no block given (yield))
>> [1, 1].inject(2, :+)
=> 4
>> [1, 1].my_inject(2, :+) #ArgumentError (wrong number of arguments (given 2, expected 0..1))
```
Status: __Request changes__.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @kelibst  :handshake: 

### Thank you for doing the changes required by the previous reviewer :medal_sports: your project is a lot functional now, is always good practice to find test cases and test your code against them so claps to you for that :clap:  :star: your project still needs work with one enumerable :construction: :construction_worker_man:  so let's work on it! :point_down: 

## my_inject

- [ ] When a symbol is provided as an argument, my_inject should combine the elements of the enum using that symbol as a named method.

     > this Array.new(1000) { rand(0...10) }.my_inject(:+) should be equal to this Array.new(1000) { rand(0...10) }.inject(:+) => 4693

- Yours is retrieving the wrong answer
image

- Real
image

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by euqueme** [comment]
### This code review should be APPROVED as it was pointed out to me by @kelibst  :bowing_woman: 

#### I performed a math random to validate my_inject is equals to inject but when

Given

> array = Array.new(1000) { rand(0...10) }

array.my_inject(:+) is equals to array.inject(:+) 

- @kelibst my_inject
image

- Real inject
image

so the next person who reviews this please approve this project :pray: :pray: :pray:

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, you are almost there. 
- [ ] `my_inject`
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
`array = (0...10)`
`p array.my_inject(2, :*) == array.inject(2, :*)` should return `true`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @kelibst  :handshake: 

### Thank you for making the previous reviewer test case work :medal_sports: , but your my_inject still doesn't pass with all ranges

## my_inject

- [ ] When a symbol is provided as an argument, my_inject should combine the elements of the enum using that symbol as a named method.

Given

`array = Range.new(5, 50)`

 > `this array.inject(2, :*) should be equal to this array.inject(2, :*) => 2534507766809448170301050680505397403698136797413376000000000000
`
- Yours is retrieving the wrong answer
image

- Real
image

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by kelibst** [comment]
I would be very grateful if you guys can just come up with the test once and for all and let me work on it until I find an answer. What shows that my next answer will not bring some totally new test fail and send us in this unending loop of rejection?
Please one test and fixes.

**Review by whiz25 — APPROVED** [review]
## Congz :clap:
All edge cases are covered and therefore it's a :+1: from me. Merge and proceed.

### Martin Afani

**Pull request merged**
